require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
  - app/**/*.rb
  - config.ru
  - config/**/*.rb
  - db/**/*.rb
  - lib/tasks/**/*.rb
  - Rakefile
  - spec/**/*.rb
  - test/**/*.rb
  - '**/Gemfile'
  Exclude:
  - bin/**/*
  - tmp/**/*
  - vendor/**/*
  - db/schema.rb
  TargetRubyVersion: 2.6
  StyleGuideCopsOnly: true
  NewCops: enable

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
Style/SymbolArray:
  # Turned off because the associated auto-correct makes a real mess
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
